# Generated by Django 4.0.2 on 2022-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_agendamento_prestador"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="cancelado",
            field=models.BooleanField(default=False),
        ),
    ]
